### PR TITLE
Complete support for genderize.io API

### LINKED ISSUE #5: name_list = Gendered::NameList.new(["Sean","Theresa"]) doesn't work
When I type name_list = Gendered::NameList.new(["Sean","Theresa"]) doesn't work , I get an error in 'lib/ruby/gems/2.2.0/gems/gendered-0.0.7/lib/gendered/guesser.rb:13:in `guess!': wrong number of arguments (1 for 0) (ArgumentError)'.

Looking at the gendered gem file, in name_list.rb, there's a NameList class with a method guess! and on line 18, it calls guess! in guesser.rb 
''''Guesser.new(slice).guess!(country_id).'''

But in guesser.rb on line 13, guess! method doesn't take in arguments.   So therein I believe is the problem.  Make guess! in guesser.rb accept an arg 'country_id', or remove it from name_list.rb line 18

### PR DESCRIPTION
**Pull request by sshaw**
This fixes #5 -which was broken by fdb5274483e238347faf4a956313efe40f5c546d- and, in some part, addresses #2 & #6. It also modifies (i.e. breaks) various calls so that they accept a `Hash` instead of a just `country_id`.

To summarize:

1. `:country_id`, `:language_id`, `:apikey`, and `:connection` are now accepted as options.
`:connection's` value will be passed to the http.rb library

2. Configuration can be done globally via `Gendered.config` or
`Gendered.configure { |cfg| ... }`

3. Request/response related errors will result in a `GenderedError`
exceptions being raised

4. Support for rubies < 2.1, namely JRuby, by removing `%i()`

Some other things to consider changing:

## Inconsistent Return Values on `Name`

`#probability` and `#sample_size` return `:unknown` if they have not been guessed, and `BigDecimal` if they have been. These should return `0` or `nil` of they cannot be guessed.

[Their setters only allow `BigDecimal`](https://github.com/sshaw/gendered/blob/v0.0.7/lib/gendered/name.rb#L26) (though why would one want to set? Shouldn't these be readonly?). 

If  not guessed `#male?` and `#female?` return `:not_guessed`. I think it makes more sense for them to always return a boolean. If it's not guessed then it's neither male nor female, so these should return `false`. 

Consistency is important, but the current behavior can lead to errors:

```ruby
name = Gendered::Name.new("Mac Dre")
name.guess!
if name.female?
  # do some thangz
end
```

## Per Request Name Limit

The API docs say that [the limit is 10 names per request](https://store.genderize.io/documentation#multipleUsage), but [the code sends 100 at a time](https://github.com/barelyknown/gendered/blob/v0.0.7/lib/gendered/name_list.rb#L17). Are the docs wrong?

### CODE REVIEW

File: lib/gendered/guesser.rb [hunk 1]
```diff
@@ -35,17 +36,41 @@ def guess!
...
-      name_queries = names.collect.with_index do |name, index|
-        "name[#{index}]=#{CGI.escape(name.to_s)}"
+      [:country_id, :language_id, :apikey].each do |param|
+        next if @options[param].nil?
+        query << sprintf("%s=%s", param.to_s, CGI.escape(@options[param].to_s))
       end
-      url + name_queries.join("&")
+
+      names.each_with_index do |name, index|
+        query << sprintf("name[%s]=%s", index, CGI.escape(name.to_s))
```
Comment (sshaw) [inline lib/gendered/guesser.rb]: Specifying the index should not be needed, but I kept it anyways, maybe I'm missing something...

**Comment by sshaw** [comment]
Also, I think that `Gendered::NameList#guess!`'s signature should match `Gendered::Name#guess!`'s.
Currently  `Gendered::NameList#guess!` takes no options whereas  `Gendered::Name#guess!` does. 

It makes more sense to model it after `Name`'s, as it's possible that one may want to check the given names across multiple lang or countries.

**Comment by barelyknown** [comment]
Thanks for these. I'll take a look and merge in the next couple of days.

**Comment by sshaw** [comment]
@barelyknown did you ever get around to having a look at this pull request?

**Comment by barelyknown** [comment]
Shoot - I didn't, but I will. Our baby twins were born two weeks ago and things have been _too busy_ for a few months!

**Comment by sshaw** [comment]
:baby: :baby:

**Comment by sshaw** [comment]
Made a few more small fixes and add some stuff I need. 

Ultimately working towards stubbing out all request.

**Comment by eygraber** [comment]
@barelyknown Can this be merged in. Unable to use `NameList` at all.

**Comment by barelyknown** [comment]
Yes, will do now.
